"""
Django settings for vibecheck project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scanner',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "scanner.middleware.SecurityHeadersMiddleware",    # ← add directly after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        # Swap for Redis in prod:
        # "BACKEND": "django.core.cache.backends.redis.RedisCache",
        # "LOCATION": "redis://127.0.0.1:6379/1",
    }
}

# ------------------------------------------------------------------
# Database
#
# Set PGHOST (plus the other PG* vars below) to switch to Postgres.
# Leave unset to use SQLite — useful for local development.
# ------------------------------------------------------------------
_pg_host = os.environ.get("PGHOST")

if _pg_host:
    DATABASES = {
        "default": {
            "ENGINE":       "django.db.backends.postgresql",
            "NAME":         os.environ.get("PGDATABASE", "vibecheck"),
            "USER":         os.environ.get("PGUSER",     "postgres"),
            "PASSWORD":     os.environ.get("PGPASSWORD", ""),
            "HOST":         _pg_host,
            "PORT":         os.environ.get("PGPORT",     "5432"),
            "CONN_MAX_AGE": 60,   # reuse connections across requests in the same process
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE":  "django.db.backends.sqlite3",
            "NAME":    BASE_DIR / "db.sqlite3",
            "OPTIONS": {"timeout": 20},
        }
    }

# Suppress the auto-field warning:
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ROOT_URLCONF = 'vibecheck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vibecheck.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Security and Session Settings

# Tells Django to trust the load balancer when it says the original request was HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Sessions — visitors keep their scan history for 90 days.
SESSION_COOKIE_AGE      = 60 * 60 * 24 * 90  # 90 days
SESSION_COOKIE_HTTPONLY = True                 # JS can't touch it
SESSION_COOKIE_SAMESITE = "Lax"               # CSRF protection

# Secure cookies flip to True automatically in production once DEBUG is False
SESSION_COOKIE_SECURE   = not DEBUG            
CSRF_COOKIE_SECURE      = not DEBUG