# Generated by Django 6.0.7 on 2026-07-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('assets_scanned', models.JSONField(blank=True, default=list)),
                ('endpoints_probed', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('evidence', models.TextField()),
                ('location', models.CharField(max_length=2000)),
                ('recommendation', models.TextField()),
                ('category', models.CharField(default='generic', max_length=50)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
            options={
                'ordering': ['severity'],
            },
        ),
    ]
