# Generated by Django 6.0.7 on 2026-07-25 11:34

import scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='slug',
            field=models.CharField(db_index=True, default=scanner.models._new_slug, max_length=20, unique=True),
        ),
    ]
